// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuinielaVinccler.UI.Web.Data;

#nullable disable

namespace QuinielaVinccler.UI.Web.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260529134827_AgregarResultadosYMarcadores")]
    partial class AgregarResultadosYMarcadores
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuinielaVinccler.UI.Web.Data.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CI")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Common");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("QuinielaVinccler.UI.Web.Data.Models.Configuracion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Clave")
                        .IsUnique();

                    b.ToTable("Configuraciones");
                });

            modelBuilder.Entity("QuinielaVinccler.UI.Web.Data.Models.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoIso")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Grupo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("QuinielaVinccler.UI.Web.Data.Models.Lote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.ToTable("Lotes");
                });

            modelBuilder.Entity("QuinielaVinccler.UI.Web.Data.Models.Partido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("EquipoGanadorId")
                        .HasColumnType("integer");

                    b.Property<int?>("EquipoLocalId")
                        .HasColumnType("integer");

                    b.Property<int?>("EquipoVisitanteId")
                        .HasColumnType("integer");

                    b.Property<string>("Fase")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaHoraUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("GolesLocal")
                        .HasColumnType("integer");

                    b.Property<int?>("GolesVisitante")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroPartido")
                        .HasColumnType("integer");

                    b.Property<string>("ResultadoGrupo")
                        .HasColumnType("text");

                    b.Property<string>("SlotLocal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SlotVisitante")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EquipoGanadorId");

                    b.HasIndex("EquipoLocalId");

                    b.HasIndex("EquipoVisitanteId");

                    b.HasIndex("Fase");

                    b.HasIndex("NumeroPartido")
                        .IsUnique();

                    b.ToTable("Partidos");
                });

            modelBuilder.Entity("QuinielaVinccler.UI.Web.Data.Models.Planilla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("LoteId")
                        .HasColumnType("integer");

                    b.Property<int>("PuntajeTotal")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("LoteId");

                    b.HasIndex("UserId");

                    b.ToTable("Planillas");
                });

            modelBuilder.Entity("QuinielaVinccler.UI.Web.Data.Models.PrediccionFinal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CampeonEquipoId")
                        .HasColumnType("integer");

                    b.Property<int?>("CuartoLugarEquipoId")
                        .HasColumnType("integer");

                    b.Property<int?>("GolesLocalGranFinal")
                        .HasColumnType("integer");

                    b.Property<int?>("GolesLocalSemi1")
                        .HasColumnType("integer");

                    b.Property<int?>("GolesLocalSemi2")
                        .HasColumnType("integer");

                    b.Property<int?>("GolesVisitanteGranFinal")
                        .HasColumnType("integer");

                    b.Property<int?>("GolesVisitanteSemi1")
                        .HasColumnType("integer");

                    b.Property<int?>("GolesVisitanteSemi2")
                        .HasColumnType("integer");

                    b.Property<int?>("MasGoleadoEquipoId")
                        .HasColumnType("integer");

                    b.Property<int?>("MasGoleadorEquipoId")
                        .HasColumnType("integer");

                    b.Property<int?>("MenosGoleadoEquipoId")
                        .HasColumnType("integer");

                    b.Property<int>("PlanillaId")
                        .HasColumnType("integer");

                    b.Property<int?>("PuntosMarcadorGranFinal")
                        .HasColumnType("integer");

                    b.Property<int?>("PuntosMarcadorSemi1")
                        .HasColumnType("integer");

                    b.Property<int?>("PuntosMarcadorSemi2")
                        .HasColumnType("integer");

                    b.Property<int?>("PuntosPosicionesFinal")
                        .HasColumnType("integer");

                    b.Property<int?>("SegundoLugarEquipoId")
                        .HasColumnType("integer");

                    b.Property<int?>("TercerLugarEquipoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CampeonEquipoId");

                    b.HasIndex("CuartoLugarEquipoId");

                    b.HasIndex("MasGoleadoEquipoId");

                    b.HasIndex("MasGoleadorEquipoId");

                    b.HasIndex("MenosGoleadoEquipoId");

                    b.HasIndex("PlanillaId")
                        .IsUnique();

                    b.HasIndex("SegundoLugarEquipoId");

                    b.HasIndex("TercerLugarEquipoId");

                    b.ToTable("PrediccionesFinal");
                });

            modelBuilder.Entity("QuinielaVinccler.UI.Web.Data.Models.PrediccionGrupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PartidoId")
                        .HasColumnType("integer");

                    b.Property<int>("PlanillaId")
                        .HasColumnType("integer");

                    b.Property<int?>("PuntosObtenidos")
                        .HasColumnType("integer");

                    b.Property<string>("ResultadoPredicho")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PartidoId");

                    b.HasIndex("PlanillaId", "PartidoId")
                        .IsUnique();

                    b.ToTable("PrediccionesGrupo");
                });

            modelBuilder.Entity("QuinielaVinccler.UI.Web.Data.Models.PrediccionKnockout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("EquipoGanadorId")
                        .HasColumnType("integer");

                    b.Property<int?>("EquipoLocalPredichoId")
                        .HasColumnType("integer");

                    b.Property<int?>("EquipoVisitantePredichoId")
                        .HasColumnType("integer");

                    b.Property<int>("PartidoId")
                        .HasColumnType("integer");

                    b.Property<int>("PlanillaId")
                        .HasColumnType("integer");

                    b.Property<int?>("PuntosObtenidos")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EquipoGanadorId");

                    b.HasIndex("EquipoLocalPredichoId");

                    b.HasIndex("EquipoVisitantePredichoId");

                    b.HasIndex("PartidoId");

                    b.HasIndex("PlanillaId", "PartidoId")
                        .IsUnique();

                    b.ToTable("PrediccionesKnockout");
                });

            modelBuilder.Entity("QuinielaVinccler.UI.Web.Data.Models.ResultadoFinal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CampeonEquipoId")
                        .HasColumnType("integer");

                    b.Property<int?>("CuartoLugarEquipoId")
                        .HasColumnType("integer");

                    b.Property<int?>("MasGoleadoEquipoId")
                        .HasColumnType("integer");

                    b.Property<int?>("MasGoleadorEquipoId")
                        .HasColumnType("integer");

                    b.Property<int?>("MenosGoleadoEquipoId")
                        .HasColumnType("integer");

                    b.Property<int?>("SegundoLugarEquipoId")
                        .HasColumnType("integer");

                    b.Property<int?>("TercerLugarEquipoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CampeonEquipoId");

                    b.HasIndex("CuartoLugarEquipoId");

                    b.HasIndex("MasGoleadoEquipoId");

                    b.HasIndex("MasGoleadorEquipoId");

                    b.HasIndex("MenosGoleadoEquipoId");

                    b.HasIndex("SegundoLugarEquipoId");

                    b.HasIndex("TercerLugarEquipoId");

                    b.ToTable("ResultadoFinal");
                });

            modelBuilder.Entity("QuinielaVinccler.UI.Web.Data.Models.Partido", b =>
                {
                    b.HasOne("QuinielaVinccler.UI.Web.Data.Models.Equipo", "EquipoGanador")
                        .WithMany()
                        .HasForeignKey("EquipoGanadorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuinielaVinccler.UI.Web.Data.Models.Equipo", "EquipoLocal")
                        .WithMany()
                        .HasForeignKey("EquipoLocalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuinielaVinccler.UI.Web.Data.Models.Equipo", "EquipoVisitante")
                        .WithMany()
                        .HasForeignKey("EquipoVisitanteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("EquipoGanador");

                    b.Navigation("EquipoLocal");

                    b.Navigation("EquipoVisitante");
                });

            modelBuilder.Entity("QuinielaVinccler.UI.Web.Data.Models.Planilla", b =>
                {
                    b.HasOne("QuinielaVinccler.UI.Web.Data.Models.Lote", "Lote")
                        .WithMany("Planillas")
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuinielaVinccler.UI.Web.Data.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Lote");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuinielaVinccler.UI.Web.Data.Models.PrediccionFinal", b =>
                {
                    b.HasOne("QuinielaVinccler.UI.Web.Data.Models.Equipo", "Campeon")
                        .WithMany()
                        .HasForeignKey("CampeonEquipoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuinielaVinccler.UI.Web.Data.Models.Equipo", "CuartoLugar")
                        .WithMany()
                        .HasForeignKey("CuartoLugarEquipoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuinielaVinccler.UI.Web.Data.Models.Equipo", "MasGoleado")
                        .WithMany()
                        .HasForeignKey("MasGoleadoEquipoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuinielaVinccler.UI.Web.Data.Models.Equipo", "MasGoleador")
                        .WithMany()
                        .HasForeignKey("MasGoleadorEquipoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuinielaVinccler.UI.Web.Data.Models.Equipo", "MenosGoleado")
                        .WithMany()
                        .HasForeignKey("MenosGoleadoEquipoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuinielaVinccler.UI.Web.Data.Models.Planilla", "Planilla")
                        .WithOne("PrediccionFinal")
                        .HasForeignKey("QuinielaVinccler.UI.Web.Data.Models.PrediccionFinal", "PlanillaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuinielaVinccler.UI.Web.Data.Models.Equipo", "SegundoLugar")
                        .WithMany()
                        .HasForeignKey("SegundoLugarEquipoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuinielaVinccler.UI.Web.Data.Models.Equipo", "TercerLugar")
                        .WithMany()
                        .HasForeignKey("TercerLugarEquipoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Campeon");

                    b.Navigation("CuartoLugar");

                    b.Navigation("MasGoleado");

                    b.Navigation("MasGoleador");

                    b.Navigation("MenosGoleado");

                    b.Navigation("Planilla");

                    b.Navigation("SegundoLugar");

                    b.Navigation("TercerLugar");
                });

            modelBuilder.Entity("QuinielaVinccler.UI.Web.Data.Models.PrediccionGrupo", b =>
                {
                    b.HasOne("QuinielaVinccler.UI.Web.Data.Models.Partido", "Partido")
                        .WithMany()
                        .HasForeignKey("PartidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuinielaVinccler.UI.Web.Data.Models.Planilla", "Planilla")
                        .WithMany("PrediccionesGrupo")
                        .HasForeignKey("PlanillaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partido");

                    b.Navigation("Planilla");
                });

            modelBuilder.Entity("QuinielaVinccler.UI.Web.Data.Models.PrediccionKnockout", b =>
                {
                    b.HasOne("QuinielaVinccler.UI.Web.Data.Models.Equipo", "EquipoGanador")
                        .WithMany()
                        .HasForeignKey("EquipoGanadorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuinielaVinccler.UI.Web.Data.Models.Equipo", "EquipoLocalPredichado")
                        .WithMany()
                        .HasForeignKey("EquipoLocalPredichoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuinielaVinccler.UI.Web.Data.Models.Equipo", "EquipoVisitantePredichado")
                        .WithMany()
                        .HasForeignKey("EquipoVisitantePredichoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuinielaVinccler.UI.Web.Data.Models.Partido", "Partido")
                        .WithMany()
                        .HasForeignKey("PartidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuinielaVinccler.UI.Web.Data.Models.Planilla", "Planilla")
                        .WithMany("PrediccionesKnockout")
                        .HasForeignKey("PlanillaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquipoGanador");

                    b.Navigation("EquipoLocalPredichado");

                    b.Navigation("EquipoVisitantePredichado");

                    b.Navigation("Partido");

                    b.Navigation("Planilla");
                });

            modelBuilder.Entity("QuinielaVinccler.UI.Web.Data.Models.ResultadoFinal", b =>
                {
                    b.HasOne("QuinielaVinccler.UI.Web.Data.Models.Equipo", "Campeon")
                        .WithMany()
                        .HasForeignKey("CampeonEquipoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuinielaVinccler.UI.Web.Data.Models.Equipo", "CuartoLugar")
                        .WithMany()
                        .HasForeignKey("CuartoLugarEquipoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuinielaVinccler.UI.Web.Data.Models.Equipo", "MasGoleado")
                        .WithMany()
                        .HasForeignKey("MasGoleadoEquipoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuinielaVinccler.UI.Web.Data.Models.Equipo", "MasGoleador")
                        .WithMany()
                        .HasForeignKey("MasGoleadorEquipoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuinielaVinccler.UI.Web.Data.Models.Equipo", "MenosGoleado")
                        .WithMany()
                        .HasForeignKey("MenosGoleadoEquipoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuinielaVinccler.UI.Web.Data.Models.Equipo", "SegundoLugar")
                        .WithMany()
                        .HasForeignKey("SegundoLugarEquipoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuinielaVinccler.UI.Web.Data.Models.Equipo", "TercerLugar")
                        .WithMany()
                        .HasForeignKey("TercerLugarEquipoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Campeon");

                    b.Navigation("CuartoLugar");

                    b.Navigation("MasGoleado");

                    b.Navigation("MasGoleador");

                    b.Navigation("MenosGoleado");

                    b.Navigation("SegundoLugar");

                    b.Navigation("TercerLugar");
                });

            modelBuilder.Entity("QuinielaVinccler.UI.Web.Data.Models.Lote", b =>
                {
                    b.Navigation("Planillas");
                });

            modelBuilder.Entity("QuinielaVinccler.UI.Web.Data.Models.Planilla", b =>
                {
                    b.Navigation("PrediccionFinal");

                    b.Navigation("PrediccionesGrupo");

                    b.Navigation("PrediccionesKnockout");
                });
#pragma warning restore 612, 618
        }
    }
}
